### ISSUE TITLE
Create layout for recordings

### ISSUE THREAD

**Issue by jmarsh24** [jmarsh24/tangocloud#328]
Recordings have a heat meter. There also is bpm. We should explore how to properly format all this data in a recording thumbnail.

![Image](https://github.com/user-attachments/assets/6e635552-de18-4bac-9c5b-6801a18cb875)

**Acceptance Criteria**
- image or figma exploration of the different ways to present this thumbnail
- take into account if there are very long titles or many singers
- what happens when there is no heat meter data (popularity_score 0)
- Adjust thumbnail size, color, typography

**Comment by eleonorapopovska** [comment]
We already covered this in issue #326.
